version: "3.8"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    network_mode: bridge
    ports:
      - 8300:80
      - 8301:443
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Warsaw
    volumes:
      - /volume1/docker/heimdall:/config
    restart: unless-stopped